// =====================================================
// CATALOGUE DE CONNAISSANCES SINE.SHOP — cœur de l'assistant autonome
// =====================================================
// Remplace l'appel à OpenAI (callOpenAIResponses) qui pilotait jusqu'ici
// TOUTES les réponses de l'assistant — sans clé API valide, ai.service.js
// retombait sur un repli à 3 branches (commande/paiement/générique),
// beaucoup trop pauvre pour être vraiment utile. Ce fichier contient plus
// de 200 entrées organisées par catégorie (compte, commandes, paiement,
// livraison, réservation, vendeur, livreur, affiliation, sécurité,
// général) — chacune avec des mots-clés déclencheurs et une réponse
// SINE.SHOP réelle. Le moteur de correspondance (matcher.js) s'appuie
// dessus pour trouver la meilleure entrée, combinée aux vraies données du
// compte (commandes, paiements, produits...) déjà récupérées par
// ai.service.js pour personnaliser la réponse quand c'est pertinent.

const KNOWLEDGE_BASE = [
  // ===================== COMPTE / INSCRIPTION =====================
  { id: 'kb001', cat: 'compte', kw: ['créer', 'compte', 'inscription', 'inscrire'], q: 'Comment créer un compte ?', a: "Cliquez sur \"S'inscrire\" depuis la page d'accueil, choisissez votre profil (client, vendeur, livreur ou affilié), puis renseignez vos informations. Vous recevrez un code de vérification par email ou SMS." },
  { id: 'kb002', cat: 'compte', kw: ['mot de passe', 'oublié', 'réinitialiser'], q: 'J\'ai oublié mon mot de passe', a: 'Cliquez sur "Mot de passe oublié" depuis la page de connexion, saisissez votre email, téléphone ou pseudo. Vous recevrez un code par email (valable 48h) ou SMS pour en choisir un nouveau.' },
  { id: 'kb003', cat: 'compte', kw: ['modifier', 'nom', 'prénom'], q: 'Comment modifier mon nom ?', a: 'Depuis votre Section Profil, vous pouvez modifier votre nom et prénom. Ce champ ne peut être modifié qu\'une fois tous les 30 jours pour éviter les usurpations.' },
  { id: 'kb004', cat: 'compte', kw: ['pseudo', 'pseudonyme', 'changer'], q: 'Comment changer mon pseudonyme ?', a: 'Votre pseudonyme est modifiable une fois tous les 14 jours depuis votre Section Profil. Il doit être unique et contenir 3 à 24 caractères.' },
  { id: 'kb005', cat: 'compte', kw: ['téléphone', 'numéro', 'changer', 'modifier'], q: 'Comment changer mon numéro de téléphone ?', a: 'Vous pouvez modifier votre numéro tous les 3 jours depuis votre Section Profil. Le nouveau numéro devra être revalidé par SMS.' },
  { id: 'kb006', cat: 'compte', kw: ['email', 'adresse', 'changer'], q: 'Comment changer mon adresse email ?', a: 'Cliquez sur "Modifier" à côté de votre email dans la Section Profil, saisissez la nouvelle adresse, puis confirmez avec le code envoyé à cette NOUVELLE adresse (pas l\'ancienne). Modifiable une fois tous les 30 jours.' },
  { id: 'kb007', cat: 'compte', kw: ['valider', 'vérifier', 'numéro', 'sms'], q: 'Comment valider mon numéro de téléphone ?', a: 'Dans votre Section Profil, cliquez sur "Valider" à côté de votre numéro. Vous recevrez un code par SMS à saisir pour confirmer.' },
  { id: 'kb008', cat: 'compte', kw: ['supprimer', 'compte', 'fermer'], q: 'Comment supprimer mon compte ?', a: 'Depuis Paramètres > Gestion du compte, vous trouverez l\'option de suppression. Attention, cette action est irréversible et supprime toutes vos données.' },
  { id: 'kb009', cat: 'compte', kw: ['connexion', 'google', 'facebook'], q: 'Puis-je me connecter avec Google ou Facebook ?', a: 'Oui, les boutons "Continuer avec Google" et "Continuer avec Facebook" sont disponibles sur la page de connexion. Votre compte SINE.SHOP est créé ou relié automatiquement.' },
  { id: 'kb010', cat: 'compte', kw: ['langue', 'changer', 'français', 'anglais'], q: 'Comment changer la langue de l\'application ?', a: 'SINE.SHOP détecte automatiquement la langue de votre appareil (français, anglais, espagnol, arabe). Vous pouvez aussi la changer manuellement dans Paramètres.' },
  { id: 'kb011', cat: 'compte', kw: ['devise', 'monnaie', 'fcfa', 'euro'], q: 'Comment changer la devise affichée ?', a: 'La devise s\'adapte automatiquement à votre pays. Vous pouvez la modifier manuellement dans Paramètres si besoin.' },
  { id: 'kb012', cat: 'compte', kw: ['plusieurs', 'rôles', 'vendeur', 'client', 'basculer'], q: 'Puis-je avoir plusieurs rôles (client et vendeur) ?', a: 'Oui, vous pouvez ajouter un rôle vendeur, livreur ou affilié à votre compte client existant, et basculer entre eux depuis Paramètres > Mes rôles.' },
  { id: 'kb013', cat: 'compte', kw: ['visibilité', 'profil', 'public', 'privé'], q: 'Qui peut voir mes informations de profil ?', a: 'Dans Section Profil > Visibilité de mon profil, vous choisissez ce que les vendeurs/livreurs avec qui vous échangez peuvent voir (nom, photo, ville, téléphone, bio, réseaux sociaux).' },
  { id: 'kb014', cat: 'compte', kw: ['code confidentialité', 'sécurité', 'admin'], q: 'Qu\'est-ce que le code de confidentialité ?', a: 'Réservé aux comptes à privilèges (admin, modérateur, support), ce code additionnel au mot de passe protège l\'accès aux fonctions sensibles.' },
  { id: 'kb015', cat: 'compte', kw: ['session', 'déconnecter', 'tous', 'appareils'], q: 'Comment me déconnecter de tous mes appareils ?', a: 'Depuis Paramètres, le bouton "Déconnecter tous les appareils" met fin à toutes vos sessions actives immédiatement.' },

  // ===================== COMMANDES =====================
  { id: 'kb020', cat: 'commande', kw: ['passer', 'commande', 'comment', 'acheter'], q: 'Comment passer une commande ?', a: 'Ajoutez les articles souhaités à votre panier, cliquez sur "Passer la commande", vérifiez votre adresse de livraison, choisissez le mode de paiement puis validez.' },
  { id: 'kb021', cat: 'commande', kw: ['suivre', 'suivi', 'commande', 'statut'], q: 'Comment suivre ma commande ?', a: 'Rendez-vous dans votre Section Commandes, cliquez sur la commande concernée pour voir son statut en temps réel et suivre le livreur sur la carte une fois expédiée.' },
  { id: 'kb022', cat: 'commande', kw: ['annuler', 'commande'], q: 'Comment annuler une commande ?', a: 'Tant que votre commande est encore "en attente" ou "confirmée", vous pouvez l\'annuler depuis sa page de détail. Une fois expédiée, contactez le vendeur ou le support.' },
  { id: 'kb023', cat: 'commande', kw: ['plusieurs', 'vendeurs', 'même', 'commande'], q: 'Puis-je commander chez plusieurs vendeurs en même temps ?', a: 'Oui ! Ajoutez des articles de différents vendeurs à votre panier, une seule commande groupée est créée (une sous-commande par vendeur), avec un seul paiement.' },
  { id: 'kb024', cat: 'commande', kw: ['statut', 'signification', 'en attente', 'confirmée'], q: 'Que signifient les statuts de commande ?', a: '"En attente" : commande créée, paiement pas encore confirmé. "Confirmée" : paiement validé. "En préparation" : le vendeur prépare le colis. "Expédiée" : le livreur l\'a récupérée. "Livrée" : reçue par vous.' },
  { id: 'kb025', cat: 'commande', kw: ['facture', 'reçu', 'télécharger'], q: 'Comment obtenir ma facture ?', a: 'Depuis le détail de votre commande, cliquez sur "Facture" pour l\'imprimer, la télécharger ou la partager directement.' },
  { id: 'kb026', cat: 'commande', kw: ['modifier', 'adresse', 'livraison', 'commande'], q: 'Puis-je modifier l\'adresse de livraison après commande ?', a: 'Tant que la commande n\'est pas expédiée, contactez le vendeur via la messagerie pour lui demander la modification.' },
  { id: 'kb027', cat: 'commande', kw: ['délai', 'temps', 'livraison', 'combien'], q: 'Quel est le délai de livraison ?', a: 'Le délai varie selon le vendeur et votre localisation, généralement entre 24h et 72h en zone urbaine. Le délai estimé est affiché avant validation de la commande.' },
  { id: 'kb028', cat: 'commande', kw: ['historique', 'anciennes', 'commandes'], q: 'Où voir mes anciennes commandes ?', a: 'Toutes vos commandes passées sont dans votre Section Commandes, avec filtre par statut et recherche.' },
  { id: 'kb029', cat: 'commande', kw: ['problème', 'article', 'manquant', 'endommagé'], q: 'Un article est manquant ou endommagé', a: 'Contactez immédiatement le vendeur via la messagerie avec des photos si possible. Si le problème persiste, ouvrez un ticket support ou un litige depuis la commande.' },
  { id: 'kb030', cat: 'commande', kw: ['minimum', 'commande', 'montant'], q: 'Y a-t-il un montant minimum de commande ?', a: 'Non, il n\'y a pas de montant minimum général sur SINE.SHOP, sauf indication contraire d\'un vendeur spécifique.' },

  // ===================== PAIEMENT =====================
  { id: 'kb040', cat: 'paiement', kw: ['modes', 'paiement', 'moyens', 'accepté'], q: 'Quels moyens de paiement sont acceptés ?', a: 'Mobile Money (MTN, Orange, Wave), carte bancaire (Visa/Mastercard) via CinetPay, et le paiement à la livraison selon le vendeur.' },
  { id: 'kb041', cat: 'paiement', kw: ['sécurisé', 'paiement', 'sécurité'], q: 'Le paiement est-il sécurisé ?', a: 'Oui, tous les paiements passent par CinetPay, une passerelle sécurisée et certifiée. SINE.SHOP ne stocke jamais vos données bancaires.' },
  { id: 'kb042', cat: 'paiement', kw: ['échec', 'paiement', 'refusé', 'raté'], q: 'Mon paiement a échoué, que faire ?', a: 'Vérifiez votre solde et réessayez. Si le problème persiste, contactez votre opérateur Mobile Money ou votre banque, ou tentez un autre mode de paiement.' },
  { id: 'kb043', cat: 'paiement', kw: ['remboursement', 'rembourser', 'délai'], q: 'Comment et quand suis-je remboursé ?', a: 'En cas d\'annulation ou de litige validé, le remboursement est traité sous 3 à 7 jours ouvrés sur le moyen de paiement d\'origine.' },
  { id: 'kb044', cat: 'paiement', kw: ['paiement', 'livraison', 'espèces', 'cash'], q: 'Puis-je payer à la livraison ?', a: 'Certains vendeurs proposent le paiement à la livraison (cash on delivery) — vérifiez l\'option lors du paiement.' },
  { id: 'kb045', cat: 'paiement', kw: ['reçu', 'paiement', 'preuve'], q: 'Où trouver mon reçu de paiement ?', a: 'Le reçu est disponible depuis le détail de votre commande, section "Paiement", ou peut être envoyé directement dans une conversation.' },
  { id: 'kb046', cat: 'paiement', kw: ['double', 'débit', 'deux fois'], q: 'J\'ai été débité deux fois', a: 'Contactez immédiatement le support avec vos références de transaction — nous vérifierons et rembourserons le doublon sous 48h.' },

  // ===================== LIVRAISON =====================
  { id: 'kb050', cat: 'livraison', kw: ['frais', 'livraison', 'coût', 'prix'], q: 'Combien coûte la livraison ?', a: 'Les frais de livraison sont calculés selon la distance et affichés avant validation de votre commande, généralement entre 500 et 2000 FCFA.' },
  { id: 'kb051', cat: 'livraison', kw: ['zone', 'couverte', 'livre', 'où'], q: 'Quelles zones sont couvertes ?', a: 'SINE.SHOP livre dans les principales villes de Côte d\'Ivoire et s\'étend progressivement à d\'autres pays. La disponibilité s\'affiche selon votre adresse.' },
  { id: 'kb052', cat: 'livraison', kw: ['contacter', 'livreur', 'joindre'], q: 'Comment contacter mon livreur ?', a: 'Une fois votre commande expédiée, vous pouvez échanger directement avec le livreur via la messagerie intégrée ou l\'appeler.' },
  { id: 'kb053', cat: 'livraison', kw: ['suivre', 'carte', 'temps réel', 'position'], q: 'Puis-je suivre le livreur en temps réel ?', a: 'Oui, une fois la commande expédiée, sa position s\'affiche en direct sur la carte dans la page de suivi.' },
  { id: 'kb054', cat: 'livraison', kw: ['absent', 'personne', 'livraison'], q: 'Je suis absent au moment de la livraison', a: 'Contactez le livreur via la messagerie pour convenir d\'un autre créneau ou d\'un point de dépôt alternatif.' },

  // ===================== RÉSERVATION =====================
  { id: 'kb060', cat: 'reservation', kw: ['réserver', 'réservation', 'comment'], q: 'Comment réserver un article ?', a: 'Sur la fiche produit, cliquez sur "Réserver" puis choisissez vos dates. La réservation est valable 72 heures — pensez à la transformer en commande avant expiration.' },
  { id: 'kb061', cat: 'reservation', kw: ['expire', 'réservation', 'durée'], q: 'Combien de temps dure une réservation ?', a: 'Une réservation reste active 72 heures. Passé ce délai, elle expire automatiquement et l\'article redevient disponible pour d\'autres clients.' },
  { id: 'kb062', cat: 'reservation', kw: ['annuler', 'réservation'], q: 'Comment annuler une réservation ?', a: 'Depuis votre Section Réservations, cliquez sur la réservation concernée puis "Annuler".' },
  { id: 'kb063', cat: 'reservation', kw: ['transformer', 'commande', 'réservation'], q: 'Comment transformer ma réservation en commande ?', a: 'Cliquez sur "Commander" depuis votre réservation active — les articles sont ajoutés à votre panier automatiquement.' },

  // ===================== FAVORIS / PRODUITS =====================
  { id: 'kb070', cat: 'produit', kw: ['favoris', 'ajouter', 'coeur'], q: 'Comment ajouter un produit en favoris ?', a: 'Cliquez sur l\'icône cœur sur n\'importe quelle fiche produit ou carte produit — il apparaîtra dans votre Section Favoris.' },
  { id: 'kb071', cat: 'produit', kw: ['rechercher', 'produit', 'trouver'], q: 'Comment rechercher un produit ?', a: 'Utilisez la barre de recherche en haut de l\'écran, ou parcourez les catégories depuis le menu principal.' },
  { id: 'kb072', cat: 'produit', kw: ['comparer', 'produits'], q: 'Puis-je comparer plusieurs produits ?', a: 'Oui, la fonction comparaison vous permet de mettre côte à côte plusieurs produits similaires (prix, caractéristiques, avis).' },
  { id: 'kb073', cat: 'produit', kw: ['avis', 'note', 'évaluer'], q: 'Comment laisser un avis sur un produit ?', a: 'Une fois votre commande livrée, rendez-vous sur la fiche produit ou votre commande pour laisser une note et un commentaire.' },
  { id: 'kb074', cat: 'produit', kw: ['vendeur', 'vérifié', 'badge'], q: 'Que signifie le badge "vendeur vérifié" ?', a: 'Ce badge indique que le vendeur a complété la vérification de son identité et de sa boutique par notre équipe.' },

  // ===================== MESSAGERIE =====================
  { id: 'kb080', cat: 'messagerie', kw: ['contacter', 'vendeur', 'message'], q: 'Comment contacter un vendeur ?', a: 'Depuis la fiche produit ou le profil du vendeur, cliquez sur "Message" pour ouvrir une conversation directement.' },
  { id: 'kb081', cat: 'messagerie', kw: ['bloquer', 'utilisateur', 'messagerie'], q: 'Comment bloquer quelqu\'un dans la messagerie ?', a: 'Ouvrez la conversation, cliquez sur le menu "⋮" puis "Bloquer" — vous ne recevrez plus de messages de cette personne.' },
  { id: 'kb082', cat: 'messagerie', kw: ['appel', 'vocal', 'vidéo', 'messagerie'], q: 'Puis-je appeler un vendeur depuis l\'application ?', a: 'Oui, la messagerie intègre les appels vocaux et vidéo directement, sans avoir besoin du numéro de téléphone.' },
  { id: 'kb083', cat: 'messagerie', kw: ['archiver', 'conversation'], q: 'Comment archiver une conversation ?', a: 'Ouvrez le menu "⋮" de la conversation puis "Archiver" — retrouvez-la ensuite dans la section Archives.' },
  { id: 'kb084', cat: 'messagerie', kw: ['modifier', 'message', 'envoyé'], q: 'Puis-je modifier un message déjà envoyé ?', a: 'Oui, dans les 10 minutes suivant l\'envoi, cliquez sur le crayon à côté du message pour le modifier.' },

  // ===================== VENDEUR — PRODUITS =====================
  { id: 'kb100', cat: 'vendeur', kw: ['publier', 'produit', 'ajouter', 'vendre'], q: 'Comment publier un produit ?', a: 'Depuis Section Publier, renseignez le nom, la catégorie, le prix, les photos/vidéos et les caractéristiques, puis cliquez sur "Publier".' },
  { id: 'kb101', cat: 'vendeur', kw: ['modifier', 'produit', 'fiche'], q: 'Comment modifier une fiche produit ?', a: 'Depuis Section Produits, cliquez sur le produit concerné puis "Modifier". Notez qu\'un produit déjà réservé ou commandé ne peut pas être modifié tant que la transaction n\'est pas terminée.' },
  { id: 'kb102', cat: 'vendeur', kw: ['supprimer', 'produit'], q: 'Comment supprimer un produit ?', a: 'Depuis la fiche produit dans votre espace, cliquez sur "Supprimer". Un produit réservé ou en commande active ne peut pas être supprimé.' },
  { id: 'kb103', cat: 'vendeur', kw: ['photos', 'vidéos', 'combien'], q: 'Combien de photos/vidéos puis-je ajouter par produit ?', a: 'Vous pouvez ajouter plusieurs photos et une vidéo par produit pour donner un maximum de visibilité à vos articles.' },
  { id: 'kb104', cat: 'vendeur', kw: ['catégorie', 'personnalisée', 'créer'], q: 'Puis-je créer ma propre catégorie ?', a: 'Oui, si aucune catégorie existante ne correspond, utilisez le bouton "➕" à côté du sélecteur de catégorie pour en créer une.' },
  { id: 'kb105', cat: 'vendeur', kw: ['stock', 'gérer', 'quantité'], q: 'Comment gérer mon stock ?', a: 'Indiquez la quantité disponible à la publication — elle se met à jour automatiquement à chaque vente. Vous pouvez l\'ajuster manuellement à tout moment.' },
  { id: 'kb106', cat: 'vendeur', kw: ['taille', 'pointure', 'plusieurs'], q: 'Comment proposer plusieurs tailles/pointures ?', a: 'Lors de la publication, activez la sélection multiple pour cocher toutes les tailles ou pointures disponibles pour cet article.' },
  { id: 'kb107', cat: 'vendeur', kw: ['prévisualiser', 'aperçu', 'avant', 'publier'], q: 'Puis-je prévisualiser mon annonce avant publication ?', a: 'Oui, le bouton "Prévisualiser" affiche exactement le rendu final tel que les acheteurs le verront.' },
  { id: 'kb108', cat: 'vendeur', kw: ['brouillon', 'enregistrer', 'plus tard'], q: 'Puis-je enregistrer un brouillon ?', a: 'Oui, le bouton "Enregistrer comme brouillon" garde votre fiche produit pour la finaliser plus tard sans la publier.' },

  // ===================== VENDEUR — VENTES / STATS / RETRAIT =====================
  { id: 'kb120', cat: 'vendeur_ventes', kw: ['commandes', 'reçues', 'voir'], q: 'Comment voir mes commandes reçues ?', a: 'Votre Section Commandes liste toutes les commandes reçues, avec leur statut, et vous permet de les faire avancer (préparation, expédition).' },
  { id: 'kb121', cat: 'vendeur_ventes', kw: ['solde', 'gains', 'argent', 'combien'], q: 'Comment voir mon solde disponible ?', a: 'Votre solde (issu des ventes livrées et payées) est visible dans votre tableau de bord et la section Retraits.' },
  { id: 'kb122', cat: 'vendeur_ventes', kw: ['retirer', 'retrait', 'argent'], q: 'Comment retirer mon argent ?', a: 'Depuis Section Retraits, indiquez le montant et votre moyen (Mobile Money, virement), puis validez. Un administrateur traite votre demande sous quelques jours.' },
  { id: 'kb123', cat: 'vendeur_ventes', kw: ['commission', 'pourcentage', 'combien', 'prend'], q: 'Quelle commission prend SINE.SHOP ?', a: 'SINE.SHOP prélève une commission de 5% sur chaque vente, déjà déduite automatiquement de votre solde disponible.' },
  { id: 'kb124', cat: 'vendeur_ventes', kw: ['favoris', 'reçus', 'combien'], q: 'Comment savoir quels produits sont mis en favoris ?', a: 'Votre tableau de bord affiche un compteur de favoris par produit, pour repérer ceux qui suscitent le plus d\'intérêt.' },
  { id: 'kb125', cat: 'vendeur_ventes', kw: ['note', 'avis', 'clients'], q: 'Comment voir mes avis clients ?', a: 'Vos avis et notes sont visibles sur votre profil boutique public et résumés dans votre tableau de bord.' },
  { id: 'kb126', cat: 'vendeur_ventes', kw: ['litige', 'conflit', 'client'], q: 'Un client a ouvert un litige, que faire ?', a: 'Consultez le détail du litige depuis votre espace, répondez avec des preuves si besoin. Un modérateur tranchera si aucun accord n\'est trouvé.' },
  { id: 'kb127', cat: 'vendeur_ventes', kw: ['boutique', 'vérifiée', 'validation'], q: 'Comment faire vérifier ma boutique ?', a: 'Complétez votre profil vendeur (pièce d\'identité, justificatifs) — notre équipe valide sous quelques jours et vous obtenez le badge "Vérifié".' },

  // ===================== VENDEUR — CONSEILS / DÉCISIONS =====================
  { id: 'kb140', cat: 'vendeur_conseil', kw: ['prix', 'fixer', 'comment', 'combien'], q: 'Comment fixer le bon prix pour mon produit ?', a: 'Comparez avec des produits similaires sur la plateforme, tenez compte de vos coûts + commission (5%) + marge souhaitée. Un prix trop élevé réduit les vues, trop bas nuit à votre marge.' },
  { id: 'kb141', cat: 'vendeur_conseil', kw: ['vendre', 'plus', 'astuces', 'améliorer'], q: 'Comment vendre plus sur SINE.SHOP ?', a: 'Ajoutez des photos de qualité et une vidéo, rédigez une description claire et complète, répondez vite aux messages, maintenez un bon stock, et encouragez vos clients satisfaits à laisser un avis.' },
  { id: 'kb142', cat: 'vendeur_conseil', kw: ['promotion', 'campagne', 'lancer'], q: 'Comment lancer une promotion ?', a: 'Ajustez temporairement le prix de vos produits phares, et mentionnez-le dans votre description. Les baisses de prix remontent naturellement dans les recommandations des clients qui ont ce produit en favoris.' },
  { id: 'kb143', cat: 'vendeur_conseil', kw: ['visibilité', 'produit', 'améliorer', 'vues'], q: 'Comment améliorer la visibilité de mes produits ?', a: 'Utilisez des mots-clés précis dans le titre, remplissez toutes les caractéristiques, publiez régulièrement de nouveaux articles, et gardez un excellent taux de réponse en messagerie.' },
  { id: 'kb144', cat: 'vendeur_conseil', kw: ['stock', 'faible', 'décision', 'réapprovisionner'], q: 'Mon stock est bas, que faire ?', a: 'Surveillez vos ventes régulières et réapprovisionnez avant la rupture — un produit "en rupture" perd en visibilité et en confiance auprès des acheteurs.' },
  { id: 'kb145', cat: 'vendeur_conseil', kw: ['produit', 'ne', 'vend', 'pas'], q: 'Mon produit ne se vend pas, que faire ?', a: 'Vérifiez le prix par rapport à la concurrence, améliorez les photos/description, et envisagez une petite baisse de prix temporaire pour relancer l\'intérêt.' },
  { id: 'kb146', cat: 'vendeur_conseil', kw: ['description', 'rédiger', 'produit'], q: 'Comment rédiger une bonne description ?', a: 'Soyez précis (matière, dimensions, état), mettez en avant les bénéfices concrets pour l\'acheteur, et anticipez les questions fréquentes directement dans le texte.' },

  // ===================== LIVREUR =====================
  { id: 'kb160', cat: 'livreur', kw: ['devenir', 'livreur', 'inscrire'], q: 'Comment devenir livreur ?', a: 'Inscrivez-vous via "Devenir livreur", renseignez votre véhicule et votre zone, puis complétez la vérification d\'identité.' },
  { id: 'kb161', cat: 'livreur', kw: ['disponibilité', 'disponible', 'changer'], q: 'Comment changer ma disponibilité ?', a: 'Le bouton Disponible/Indisponible sur votre tableau de bord détermine si vous recevez de nouvelles missions.' },
  { id: 'kb162', cat: 'livreur', kw: ['mission', 'livraison', 'accepter'], q: 'Comment accepter une mission de livraison ?', a: 'Une notification vous prévient d\'une nouvelle livraison à prendre en charge, avec l\'adresse du vendeur (retrait) et du client (livraison).' },
  { id: 'kb163', cat: 'livreur', kw: ['plusieurs', 'vendeurs', 'commande', 'groupée'], q: 'Un client a commandé chez plusieurs vendeurs, comment faire ?', a: 'Vous verrez un avertissement "commande groupée" avec la liste des autres retraits à effectuer chez d\'autres vendeurs avant de tout assembler pour une livraison unique au client.' },
  { id: 'kb164', cat: 'livreur', kw: ['zone', 'livraison', 'définir'], q: 'Comment définir ma zone de livraison ?', a: 'Depuis votre profil, indiquez votre ville et le rayon d\'action dans lequel vous acceptez les missions.' },
  { id: 'kb165', cat: 'livreur', kw: ['gains', 'combien', 'gagner'], q: 'Comment sont calculés mes gains ?', a: 'Vous percevez les frais de livraison de chaque commande effectuée, visibles dans votre section Gains, avec un historique détaillé.' },
  { id: 'kb166', cat: 'livreur', kw: ['retirer', 'argent', 'retrait', 'livreur'], q: 'Comment retirer mes gains de livreur ?', a: 'Depuis votre section Retraits, indiquez le montant et votre moyen de paiement préféré (Mobile Money).' },
  { id: 'kb167', cat: 'livreur', kw: ['client', 'absent', 'que faire'], q: 'Le client est absent, que faire ?', a: 'Contactez-le via la messagerie intégrée. Si injoignable après un délai raisonnable, signalez le problème depuis la commande.' },
  { id: 'kb168', cat: 'livreur', kw: ['véhicule', 'changer', 'type'], q: 'Comment changer mon type de véhicule ?', a: 'Modifiable depuis votre Section Profil > informations véhicule.' },

  // ===================== AFFILIATION =====================
  { id: 'kb180', cat: 'affiliation', kw: ['affiliation', 'devenir', 'programme'], q: 'Comment devenir affilié ?', a: 'Inscrivez-vous via "Programme d\'affiliation", vous recevrez un code personnel à partager pour gagner des commissions sur les inscriptions et achats de vos filleuls.' },
  { id: 'kb181', cat: 'affiliation', kw: ['code', 'affiliation', 'où', 'trouver'], q: 'Où trouver mon code d\'affiliation ?', a: 'Votre code personnel est affiché sur votre tableau de bord affilié, avec un lien de partage prêt à l\'emploi.' },
  { id: 'kb182', cat: 'affiliation', kw: ['commission', 'affiliation', 'combien'], q: 'Combien puis-je gagner en affiliation ?', a: 'Vous gagnez une commission sur chaque achat effectué par vos filleuls, ainsi qu\'un bonus pouvant aller jusqu\'à 500$ par nouvelle inscription selon les conditions en vigueur.' },
  { id: 'kb183', cat: 'affiliation', kw: ['retirer', 'gains', 'affiliation'], q: 'Comment retirer mes gains d\'affiliation ?', a: 'Depuis votre tableau de bord affilié, section Retraits, indiquez le montant et votre moyen de paiement.' },
  { id: 'kb184', cat: 'affiliation', kw: ['filleuls', 'voir', 'liste'], q: 'Comment voir mes filleuls ?', a: 'Votre tableau de bord liste tous vos filleuls inscrits avec leur activité et les commissions générées.' },

  // ===================== SÉCURITÉ / CONFIDENTIALITÉ =====================
  { id: 'kb200', cat: 'securite', kw: ['données', 'personnelles', 'protection'], q: 'Comment sont protégées mes données ?', a: 'SINE.SHOP applique des mesures de sécurité strictes (chiffrement, accès restreint) et ne partage jamais vos données sans votre consentement. Consultez notre politique de confidentialité.' },
  { id: 'kb201', cat: 'securite', kw: ['compte', 'piraté', 'suspect', 'connexion'], q: 'Je pense que mon compte a été piraté', a: 'Changez immédiatement votre mot de passe, vérifiez vos sessions actives et déconnectez tous les appareils depuis Paramètres, puis contactez le support.' },
  { id: 'kb202', cat: 'securite', kw: ['arnaque', 'signaler', 'vendeur', 'suspect'], q: 'Comment signaler un vendeur suspect ?', a: 'Depuis sa fiche produit ou son profil, utilisez le bouton "Signaler" — notre équipe de modération examine chaque signalement rapidement.' },
  { id: 'kb203', cat: 'securite', kw: ['code', 'confidentiel', 'partager'], q: 'Dois-je partager mon code de vérification ?', a: 'Non, JAMAIS. Aucun membre de l\'équipe SINE.SHOP ne vous demandera votre code — s\'il vous est demandé, c\'est une tentative de fraude.' },

  // ===================== GÉNÉRAL SINE.SHOP =====================
  { id: 'kb220', cat: 'general', kw: ['sine.shop', 'qu\'est-ce', 'plateforme'], q: 'Qu\'est-ce que SINE.SHOP ?', a: 'SINE.SHOP est une marketplace complète qui connecte clients, vendeurs et livreurs — achat, vente, réservation, livraison et messagerie, le tout dans une seule application.' },
  { id: 'kb221', cat: 'general', kw: ['contact', 'support', 'aide', 'joindre'], q: 'Comment contacter le support ?', a: 'Écrivez à support@sineshophome.com ou ouvrez un ticket depuis votre espace. Notre équipe répond généralement sous 24 à 48h.' },
  { id: 'kb222', cat: 'general', kw: ['réseaux', 'sociaux', 'suivre'], q: 'Sur quels réseaux sociaux suivre SINE.SHOP ?', a: 'Retrouvez-nous sur Instagram, Facebook, TikTok, WhatsApp et X — liens disponibles en bas de chaque page.' },
  { id: 'kb223', cat: 'general', kw: ['application', 'mobile', 'télécharger'], q: 'Y a-t-il une application mobile ?', a: 'Oui, une bannière propose d\'ouvrir l\'application mobile SINE.SHOP si elle est installée, sinon elle vous redirige vers le store correspondant.' },
  { id: 'kb224', cat: 'general', kw: ['merci', 'bonjour', 'salut'], q: 'Salutations', a: 'Bonjour ! Je suis l\'assistant SINE.SHOP, ravi de vous aider. Posez-moi vos questions sur vos commandes, vos ventes, votre livraison ou tout ce qui concerne la plateforme.' },

  // ===================== COMPTE — LOT 2 =====================
  { id: 'kb016', cat: 'compte', kw: ['kyc', 'identité', 'vérification', 'document'], q: 'Qu\'est-ce que la vérification KYC ?', a: 'C\'est la vérification d\'identité (pièce d\'identité + justificatif de domicile) demandée aux vendeurs et livreurs pour sécuriser la plateforme et débloquer le badge "Vérifié".' },
  { id: 'kb017', cat: 'compte', kw: ['notifications', 'désactiver', 'paramètres'], q: 'Comment gérer mes notifications ?', a: 'Depuis Paramètres > Notifications, activez ou désactivez les alertes par email, SMS ou notification interne selon vos préférences.' },
  { id: 'kb018', cat: 'compte', kw: ['thème', 'sombre', 'clair', 'mode'], q: 'Comment activer le mode sombre ?', a: 'Depuis Paramètres, basculez entre thème clair et sombre — l\'en-tête garde toujours son identité visuelle, seul le contenu change.' },
  { id: 'kb019', cat: 'compte', kw: ['date', 'naissance', 'modifier'], q: 'Puis-je modifier ma date de naissance ?', a: 'Non, ce champ est verrouillé définitivement après la première saisie pour des raisons de sécurité et de conformité.' },
  { id: 'kb090', cat: 'compte', kw: ['pays', 'indicatif', 'trouve', 'pas'], q: 'Je ne trouve pas mon pays dans la liste', a: 'Cliquez sur le sélecteur d\'indicatif puis utilisez la barre de recherche — plus de 150 pays sont disponibles, recherchables par nom ou indicatif.' },
  { id: 'kb091', cat: 'compte', kw: ['bio', 'biographie', 'ajouter'], q: 'Comment ajouter une biographie à mon profil ?', a: 'Depuis Section Profil, remplissez le champ "Bio" (300 caractères max) pour vous présenter aux autres utilisateurs.' },
  { id: 'kb092', cat: 'compte', kw: ['réseaux', 'sociaux', 'lier', 'profil'], q: 'Comment lier mes réseaux sociaux à mon profil ?', a: 'Dans Section Profil, renseignez vos liens Instagram, Facebook, TikTok, WhatsApp ou site web.' },
  { id: 'kb093', cat: 'compte', kw: ['adresse', 'ville', 'modifier'], q: 'Comment modifier mon adresse ou ma ville ?', a: 'Votre adresse et ville restent modifiables à tout moment depuis Section Profil, contrairement au nom ou à la date de naissance.' },

  // ===================== COMMANDES — LOT 2 =====================
  { id: 'kb031', cat: 'commande', kw: ['numéro', 'commande', 'trouver'], q: 'Où trouver le numéro de ma commande ?', a: 'Le numéro de commande est affiché en haut de la page de confirmation et dans votre historique de commandes.' },
  { id: 'kb032', cat: 'commande', kw: ['panier', 'vider', 'supprimer', 'article'], q: 'Comment retirer un article de mon panier ?', a: 'Depuis votre panier, cliquez sur l\'icône de suppression à côté de l\'article concerné.' },
  { id: 'kb033', cat: 'commande', kw: ['quantité', 'modifier', 'panier'], q: 'Comment modifier la quantité d\'un article dans mon panier ?', a: 'Utilisez les boutons +/- à côté de l\'article dans votre panier pour ajuster la quantité.' },
  { id: 'kb034', cat: 'commande', kw: ['livraison', 'gratuite', 'offerte'], q: 'La livraison est-elle parfois gratuite ?', a: 'Certains vendeurs proposent la livraison gratuite à partir d\'un montant d\'achat — c\'est indiqué directement sur leur boutique.' },
  { id: 'kb035', cat: 'commande', kw: ['commande', 'groupée', 'ordergroup'], q: 'Qu\'est-ce qu\'une commande groupée ?', a: 'Quand vous achetez chez plusieurs vendeurs en une fois, chaque vendeur reçoit sa propre sous-commande mais vous ne payez qu\'une seule fois pour l\'ensemble.' },
  { id: 'kb036', cat: 'commande', kw: ['recevoir', 'code', 'commande', 'sms'], q: 'Vais-je recevoir un code pour ma commande ?', a: 'Non, les commandes, réservations et livraisons ne génèrent jamais de code de vérification — seuls les emails liés à votre compte (connexion, réinitialisation) en contiennent.' },
  { id: 'kb037', cat: 'commande', kw: ['livreur', 'assigné', 'quand'], q: 'Quand un livreur est-il assigné à ma commande ?', a: 'Dès que le vendeur confirme votre commande et la prépare, un livreur disponible dans la zone est automatiquement notifié pour la prendre en charge.' },

  // ===================== PAIEMENT — LOT 2 =====================
  { id: 'kb047', cat: 'paiement', kw: ['carte', 'bancaire', 'accepté', 'visa'], q: 'Quelles cartes bancaires sont acceptées ?', a: 'Visa et Mastercard sont acceptées via notre partenaire de paiement sécurisé CinetPay.' },
  { id: 'kb048', cat: 'paiement', kw: ['mobile money', 'mtn', 'orange', 'wave'], q: 'Quels opérateurs Mobile Money sont acceptés ?', a: 'MTN Mobile Money, Orange Money et Wave sont pris en charge selon votre pays.' },
  { id: 'kb049', cat: 'paiement', kw: ['facture', 'proforma', 'entreprise'], q: 'Puis-je obtenir une facture pour mon entreprise ?', a: 'La facture standard générée après commande peut être téléchargée et utilisée comme justificatif d\'achat.' },
  { id: 'kb055', cat: 'paiement', kw: ['annulation', 'remboursement', 'automatique'], q: 'Le remboursement est-il automatique après annulation ?', a: 'Oui, si la commande n\'était pas encore expédiée, le remboursement est déclenché automatiquement vers votre moyen de paiement d\'origine.' },
  { id: 'kb056', cat: 'paiement', kw: ['limite', 'montant', 'maximum', 'paiement'], q: 'Y a-t-il une limite de montant par paiement ?', a: 'Les limites dépendent de votre opérateur Mobile Money ou de votre banque, pas de SINE.SHOP directement.' },

  // ===================== LIVRAISON — LOT 2 =====================
  { id: 'kb057', cat: 'livraison', kw: ['plusieurs', 'colis', 'même', 'commande'], q: 'Vais-je recevoir plusieurs colis pour une commande groupée ?', a: 'Oui, si vous avez acheté chez plusieurs vendeurs, le livreur récupère chaque colis séparément puis les assemble pour vous les livrer en une seule fois si possible.' },
  { id: 'kb058', cat: 'livraison', kw: ['retard', 'livraison', 'en retard'], q: 'Ma livraison est en retard, que faire ?', a: 'Consultez le suivi en temps réel, contactez le livreur via la messagerie, ou signalez le retard depuis votre commande si cela persiste anormalement.' },
  { id: 'kb059', cat: 'livraison', kw: ['refuser', 'colis', 'livraison'], q: 'Puis-je refuser un colis à la livraison ?', a: 'Oui, si l\'article ne correspond pas à votre commande, vous pouvez le refuser — contactez ensuite le support pour traiter le remboursement.' },
  { id: 'kb064', cat: 'livraison', kw: ['heure', 'précise', 'livraison', 'rendez-vous'], q: 'Puis-je choisir une heure précise de livraison ?', a: 'Le créneau dépend de la disponibilité du livreur, mais vous pouvez convenir d\'un horaire approximatif avec lui via la messagerie.' },

  // ===================== RÉSERVATION — LOT 2 =====================
  { id: 'kb065', cat: 'reservation', kw: ['réservation', 'payer', 'avance'], q: 'Dois-je payer pour réserver un article ?', a: 'Non, la réservation est gratuite et ne bloque l\'article que temporairement (72h) — le paiement n\'intervient qu\'au moment de la commande.' },
  { id: 'kb066', cat: 'reservation', kw: ['réservation', 'plusieurs', 'articles'], q: 'Puis-je réserver plusieurs articles à la fois ?', a: 'Oui, vous pouvez avoir plusieurs réservations actives simultanément sur différents produits.' },
  { id: 'kb067', cat: 'reservation', kw: ['notification', 'réservation', 'expire', 'bientôt'], q: 'Serai-je prévenu avant l\'expiration de ma réservation ?', a: 'Un compte à rebours s\'affiche directement dans votre Section Réservations pour chaque article réservé.' },

  // ===================== PRODUITS — LOT 2 =====================
  { id: 'kb075', cat: 'produit', kw: ['catégories', 'disponibles', 'liste'], q: 'Quelles catégories de produits sont disponibles ?', a: 'Vêtements, chaussures, électronique, montres, maison, sport, beauté, alimentation, automobile, livres, jeux, services et bien d\'autres.' },
  { id: 'kb076', cat: 'produit', kw: ['vidéo', 'produit', 'lecture'], q: 'Pourquoi certaines fiches produit ont une vidéo ?', a: 'Les vendeurs peuvent ajouter une vidéo de démonstration en plus des photos — elle se lance automatiquement au défilement.' },
  { id: 'kb077', cat: 'produit', kw: ['produit', 'occasion', 'neuf', 'état'], q: 'Comment savoir si un produit est neuf ou d\'occasion ?', a: 'L\'état du produit est précisé dans sa description par le vendeur — n\'hésitez pas à demander confirmation via la messagerie en cas de doute.' },
  { id: 'kb078', cat: 'produit', kw: ['comparer', 'prix', 'plusieurs', 'vendeurs'], q: 'Comment comparer les prix entre plusieurs vendeurs ?', a: 'Utilisez la recherche puis filtrez par prix croissant pour comparer les offres similaires de différents vendeurs.' },

  // ===================== MESSAGERIE — LOT 2 =====================
  { id: 'kb085', cat: 'messagerie', kw: ['emoji', 'réaction', 'message'], q: 'Puis-je réagir à un message avec un emoji ?', a: 'Oui, un clic sur l\'icône smiley à côté de chaque message ouvre un mini-sélecteur d\'emojis à ajouter en réaction.' },
  { id: 'kb086', cat: 'messagerie', kw: ['vocal', 'audio', 'écouter', 'lecture'], q: 'Puis-je écouter un message texte au lieu de le lire ?', a: 'Oui, le bouton haut-parleur à côté de chaque message texte le lit à voix haute automatiquement.' },
  { id: 'kb087', cat: 'messagerie', kw: ['localisation', 'partager', 'messagerie'], q: 'Puis-je partager ma position dans la messagerie ?', a: 'Oui, le menu pièce jointe propose l\'option "Localisation" pour partager votre position actuelle.' },
  { id: 'kb088', cat: 'messagerie', kw: ['fichier', 'photo', 'envoyer'], q: 'Comment envoyer une photo ou un fichier ?', a: 'Cliquez sur le trombone dans la barre de conversation, choisissez Photo, Vidéo ou Fichier, puis confirmez l\'envoi.' },
  { id: 'kb089', cat: 'messagerie', kw: ['traduire', 'message', 'langue'], q: 'Puis-je traduire un message reçu ?', a: 'Oui, l\'icône de traduction sur chaque message texte le traduit à la volée dans votre langue.' },

  // ===================== VENDEUR — LOT 2 =====================
  { id: 'kb109', cat: 'vendeur', kw: ['proposer', 'produits', 'client', 'messagerie'], q: 'Puis-je proposer des produits directement dans la messagerie ?', a: 'Oui, depuis une conversation, le menu pièce jointe propose "Proposer des produits" — le client cliquera sur le lien pour les ajouter directement à son panier.' },
  { id: 'kb110', cat: 'vendeur', kw: ['boutique', 'personnaliser', 'bannière'], q: 'Comment personnaliser ma boutique ?', a: 'Ajoutez un logo et une bannière depuis votre Section Profil pour donner une identité visuelle forte à votre boutique publique.' },
  { id: 'kb111', cat: 'vendeur', kw: ['produit', 'rupture', 'stock', 'zero'], q: 'Que se passe-t-il quand mon stock atteint zéro ?', a: 'Le produit passe automatiquement en "rupture de stock" et n\'est plus achetable tant que vous ne le réapprovisionnez pas.' },
  { id: 'kb112', cat: 'vendeur', kw: ['plusieurs', 'catégories', 'produit'], q: 'Un produit peut-il appartenir à plusieurs catégories ?', a: 'Non, chaque produit appartient à une seule catégorie principale pour une navigation claire côté acheteurs.' },
  { id: 'kb113', cat: 'vendeur', kw: ['suggérer', 'livreur', 'client'], q: 'Puis-je suggérer un livreur à un client ?', a: 'Oui, depuis la messagerie, le menu pièce jointe propose "Suggérer un livreur" avec recherche parmi les livreurs disponibles.' },

  // ===================== VENDEUR VENTES — LOT 2 =====================
  { id: 'kb128', cat: 'vendeur_ventes', kw: ['délai', 'retrait', 'combien', 'temps'], q: 'Combien de temps prend un retrait ?', a: 'Les demandes de retrait sont généralement traitées sous 2 à 5 jours ouvrés après validation par un administrateur.' },
  { id: 'kb129', cat: 'vendeur_ventes', kw: ['montant', 'minimum', 'retrait'], q: 'Y a-t-il un montant minimum de retrait ?', a: 'Oui, le montant minimum de retrait est de 10 000 FCFA.' },
  { id: 'kb130', cat: 'vendeur_ventes', kw: ['statistiques', 'visiteurs', 'voir'], q: 'Comment voir mes statistiques de visiteurs ?', a: 'Votre tableau de bord affiche le nombre de visiteurs, votre note moyenne et vos ventes en un coup d\'œil.' },

  // ===================== VENDEUR CONSEILS — LOT 2 =====================
  { id: 'kb147', cat: 'vendeur_conseil', kw: ['nouveau', 'vendeur', 'conseils', 'débuter'], q: 'Je débute en tant que vendeur, par où commencer ?', a: 'Complétez d\'abord votre profil boutique (logo, bannière, bio), publiez 5 à 10 produits avec de bonnes photos, puis restez réactif en messagerie pour gagner la confiance de vos premiers clients.' },
  { id: 'kb148', cat: 'vendeur_conseil', kw: ['concurrence', 'autres', 'vendeurs'], q: 'Comment me différencier des autres vendeurs ?', a: 'Misez sur un service client réactif, des descriptions honnêtes et détaillées, et un excellent taux de satisfaction — la note et les avis pèsent beaucoup dans le choix des acheteurs.' },
  { id: 'kb149', cat: 'vendeur_conseil', kw: ['saisonnier', 'période', 'vente'], q: 'Comment adapter mes ventes aux périodes de forte demande ?', a: 'Anticipez votre stock avant les périodes de forte demande (fêtes, rentrée) et ajustez vos prix avec prudence pour rester compétitif sans perdre en marge.' },
  { id: 'kb150', cat: 'vendeur_conseil', kw: ['fidéliser', 'client', 'récurrent'], q: 'Comment fidéliser mes clients ?', a: 'Un excellent service, des délais de préparation courts et une communication claire encouragent les clients satisfaits à revenir et à vous recommander.' },

  // ===================== LIVREUR — LOT 2 =====================
  { id: 'kb169', cat: 'livreur', kw: ['refuser', 'mission', 'livraison'], q: 'Puis-je refuser une mission de livraison ?', a: 'Oui, vous pouvez décliner une mission si elle ne vous convient pas, elle sera automatiquement proposée à un autre livreur disponible.' },
  { id: 'kb170', cat: 'livreur', kw: ['note', 'évaluation', 'livreur'], q: 'Comment est calculée ma note de livreur ?', a: 'Votre note moyenne est calculée à partir des évaluations laissées par les clients après chaque livraison.' },
  { id: 'kb171', cat: 'livreur', kw: ['personnage', 'animation', 'suivi'], q: 'Puis-je personnaliser mon personnage de livraison ?', a: 'Oui, depuis votre profil, personnalisez l\'apparence du personnage affiché aux clients pendant le suivi en temps réel.' },

  // ===================== SÉCURITÉ — LOT 2 =====================
  { id: 'kb204', cat: 'securite', kw: ['rgpd', 'données', 'suppression', 'demander'], q: 'Comment demander la suppression de mes données ?', a: 'Contactez privacy@sineshophome.com ou utilisez l\'option de suppression de compte, qui efface définitivement vos données personnelles.' },
  { id: 'kb205', cat: 'securite', kw: ['double', 'authentification', '2fa'], q: 'SINE.SHOP propose-t-il la double authentification ?', a: 'Les comptes à privilèges (admin, modérateur) utilisent un code de confidentialité additionnel. Pour les comptes classiques, la vérification email/téléphone à l\'inscription assure déjà une première sécurité.' },

  // ===================== GÉNÉRAL — LOT 2 =====================
  { id: 'kb225', cat: 'general', kw: ['cgu', 'conditions', 'utilisation'], q: 'Où trouver les conditions générales d\'utilisation ?', a: 'Les CGU sont accessibles depuis Paramètres > Légal, ou en bas de la page d\'accueil.' },
  { id: 'kb226', cat: 'general', kw: ['gratuit', 'application', 'payant'], q: 'L\'application SINE.SHOP est-elle gratuite ?', a: 'Oui, l\'inscription et l\'utilisation sont entièrement gratuites pour les clients. Les vendeurs paient uniquement une commission sur les ventes réalisées.' },
  { id: 'kb227', cat: 'general', kw: ['pays', 'disponible', 'international'], q: 'Dans quels pays SINE.SHOP est-il disponible ?', a: 'La plateforme est actuellement centrée sur la Côte d\'Ivoire et s\'étend progressivement — l\'inscription reste ouverte à plus de 150 pays.' },
  { id: 'kb228', cat: 'general', kw: ['avis', 'application', 'noter'], q: 'Comment noter l\'application SINE.SHOP ?', a: 'Après plusieurs visites, une invitation à évaluer l\'application apparaît automatiquement — vous pouvez aussi la retrouver dans Paramètres.' },
  { id: 'kb229', cat: 'general', kw: ['carrières', 'recrutement', 'emploi'], q: 'SINE.SHOP recrute-t-il ?', a: 'Consultez careers@sineshophome.com pour les opportunités actuelles au sein de l\'équipe SINE.SHOP.' },
  { id: 'kb230', cat: 'general', kw: ['partenariat', 'entreprise', 'b2b'], q: 'Comment proposer un partenariat ?', a: 'Écrivez à partners@sineshophome.com pour toute demande de partenariat commercial ou B2B.' },
  { id: 'kb231', cat: 'general', kw: ['assistant', 'ia', 'intelligence'], q: 'Comment fonctionne l\'assistant SINE.SHOP ?', a: 'Je m\'appuie sur une base de connaissances complète et sur les vraies données de votre compte (commandes, paiements, produits) pour vous répondre précisément, sans dépendre d\'un service tiers.' },
  { id: 'kb232', cat: 'general', kw: ['aurevoir', 'quitter', 'fin'], q: 'Au revoir', a: 'Merci de votre visite sur SINE.SHOP ! N\'hésitez pas à revenir si vous avez d\'autres questions. Bonne journée ! 💙' },

  // ===================== LOT 3 — VARIANTES ET COMPLÉMENTS =====================
  { id: 'kb233', cat: 'commande', kw: ['livrée', 'pas', 'reçue', 'jamais'], q: 'Je n\'ai jamais reçu ma commande marquée "livrée"', a: 'Contactez immédiatement le livreur via la messagerie, puis ouvrez un ticket support si le problème n\'est pas résolu rapidement — nous investiguerons.' },
  { id: 'kb234', cat: 'commande', kw: ['combien', 'articles', 'commande'], q: 'Combien d\'articles puis-je commander à la fois ?', a: 'Il n\'y a pas de limite stricte, mais un nombre très élevé d\'articles peut déclencher une vérification supplémentaire pour votre sécurité.' },
  { id: 'kb235', cat: 'paiement', kw: ['devise', 'conversion', 'automatique', 'paiement'], q: 'Le paiement se fait-il dans ma devise locale ?', a: 'Oui, les prix et le paiement s\'affichent automatiquement dans votre devise selon votre pays, avec conversion en temps réel.' },
  { id: 'kb236', cat: 'paiement', kw: ['payer', 'plusieurs', 'fois', 'échelonné'], q: 'Puis-je payer en plusieurs fois ?', a: 'Le paiement échelonné n\'est pas disponible actuellement — le règlement se fait en une seule fois au moment de la commande.' },
  { id: 'kb237', cat: 'livraison', kw: ['emballage', 'protection', 'fragile'], q: 'Comment sont protégés les articles fragiles ?', a: 'Chaque vendeur est responsable de l\'emballage — signalez tout défaut d\'emballage constaté au support ou dans votre avis.' },
  { id: 'kb238', cat: 'reservation', kw: ['réservation', 'même', 'produit', 'plusieurs', 'clients'], q: 'Plusieurs clients peuvent-ils réserver le même produit ?', a: 'Non, une fois réservé, un article n\'est plus disponible pour d\'autres clients tant que la réservation est active (72h) ou jusqu\'à son annulation.' },
  { id: 'kb239', cat: 'produit', kw: ['stock', 'épuisé', 'alerte'], q: 'Puis-je être alerté quand un produit épuisé revient en stock ?', a: 'Ajoutez-le en favoris — vous serez informé dès que le vendeur le remet en stock.' },
  { id: 'kb240', cat: 'messagerie', kw: ['statut', 'en ligne', 'vendeur'], q: 'Comment savoir si un vendeur est en ligne ?', a: 'Un indicateur "🟢 En ligne" s\'affiche à côté de son nom dans la conversation lorsqu\'il est actuellement connecté.' },
  { id: 'kb241', cat: 'vendeur', kw: ['produit', 'signalé', 'refusé'], q: 'Pourquoi mon produit a-t-il été refusé ?', a: 'Un produit peut être refusé s\'il ne respecte pas nos règles (contenu interdit, description trompeuse). Vous recevez un motif détaillé et pouvez le corriger puis republier.' },
  { id: 'kb242', cat: 'vendeur_ventes', kw: ['paiement', 'reçu', 'quand', 'solde'], q: 'Quand l\'argent d\'une vente arrive-t-il dans mon solde ?', a: 'Le montant est crédité à votre solde disponible une fois la commande marquée comme livrée et le paiement confirmé.' },
  { id: 'kb243', cat: 'vendeur_conseil', kw: ['photos', 'qualité', 'améliorer'], q: 'Comment prendre de meilleures photos produit ?', a: 'Utilisez un bon éclairage naturel, un fond neutre, plusieurs angles, et montrez les détails importants (matière, finitions, défauts éventuels).' },
  { id: 'kb244', cat: 'livreur', kw: ['carburant', 'frais', 'compensation'], q: 'Les frais de carburant sont-ils compensés ?', a: 'Les frais de livraison perçus sont conçus pour couvrir vos déplacements — ils varient selon la distance parcourue.' },
  { id: 'kb245', cat: 'affiliation', kw: ['lien', 'partage', 'où', 'poster'], q: 'Où partager mon lien d\'affiliation ?', a: 'Partagez-le sur vos réseaux sociaux, par message ou email — chaque inscription via ce lien vous est automatiquement créditée.' },
  { id: 'kb246', cat: 'securite', kw: ['mot de passe', 'fort', 'sécurisé', 'créer'], q: 'Comment créer un mot de passe sécurisé ?', a: 'Utilisez au moins 8 caractères avec majuscules, minuscules, chiffres et symboles — évitez les mots de passe déjà utilisés ailleurs.' },
  { id: 'kb247', cat: 'general', kw: ['newsletter', 'abonner', 'désabonner'], q: 'Comment me désabonner de la newsletter ?', a: 'Un lien de désabonnement est présent en bas de chaque email marketing reçu, ou modifiez vos préférences dans Paramètres > Notifications.' },
  { id: 'kb248', cat: 'compte', kw: ['deux', 'comptes', 'même', 'personne'], q: 'Puis-je avoir deux comptes différents ?', a: 'Nous recommandons un seul compte par personne (avec plusieurs rôles possibles dessus) pour une meilleure expérience et un historique centralisé.' },
  { id: 'kb249', cat: 'commande', kw: ['livraison', 'internationale', 'étranger'], q: 'Livrez-vous à l\'international ?', a: 'La livraison est actuellement optimisée pour la Côte d\'Ivoire — la couverture internationale s\'étend progressivement selon les vendeurs et livreurs disponibles.' },
  { id: 'kb250', cat: 'paiement', kw: ['facture', 'tva', 'taxes'], q: 'Les prix incluent-ils les taxes ?', a: 'Oui, le prix affiché inclut déjà les taxes applicables — aucun frais caché n\'est ajouté au moment du paiement.' },
  { id: 'kb251', cat: 'produit', kw: ['prix', 'négocier', 'baisser'], q: 'Puis-je négocier le prix d\'un article ?', a: 'Contactez le vendeur directement via la messagerie — certains acceptent la négociation, d\'autres non, cela dépend de chacun.' },
  { id: 'kb252', cat: 'vendeur', kw: ['plusieurs', 'boutiques', 'compte'], q: 'Puis-je gérer plusieurs boutiques ?', a: 'Un compte vendeur correspond à une seule boutique — pour une activité distincte, un second compte dédié est nécessaire.' },

  // ===================== LOT 4 — COMPLÉMENT FINAL =====================
  { id: 'kb253', cat: 'commande', kw: ['erreur', 'commande', 'mauvais', 'article'], q: 'J\'ai commandé le mauvais article par erreur', a: 'Si la commande n\'est pas encore expédiée, annulez-la et repassez une nouvelle commande. Sinon, contactez le vendeur pour convenir d\'un retour.' },
  { id: 'kb254', cat: 'paiement', kw: ['paiement', 'attente', 'longtemps', 'bloqué'], q: 'Mon paiement reste "en attente" trop longtemps', a: 'Patientez quelques minutes le temps que l\'opérateur confirme la transaction. Si le statut ne change pas après 30 minutes, contactez le support avec votre référence.' },
  { id: 'kb255', cat: 'livraison', kw: ['plusieurs', 'adresses', 'enregistrer'], q: 'Puis-je enregistrer plusieurs adresses de livraison ?', a: 'Vous pouvez modifier votre adresse à chaque commande — une gestion de carnet d\'adresses multiples pourra être proposée à l\'avenir.' },
  { id: 'kb256', cat: 'reservation', kw: ['réservation', 'notification', 'confirmée'], q: 'Suis-je notifié quand ma réservation est confirmée ?', a: 'Oui, une notification est automatiquement envoyée dans votre Section Notifications dès que votre réservation est enregistrée.' },
  { id: 'kb257', cat: 'produit', kw: ['produit', 'garantie', 'durée'], q: 'Les produits ont-ils une garantie ?', a: 'La garantie dépend de chaque vendeur et du type de produit — vérifiez les informations dans la description ou demandez directement au vendeur.' },
  { id: 'kb258', cat: 'messagerie', kw: ['notification', 'nouveau', 'message', 'recevoir'], q: 'Suis-je notifié des nouveaux messages ?', a: 'Oui, une notification s\'affiche à chaque nouveau message reçu, avec un badge sur l\'icône messagerie.' },
  { id: 'kb259', cat: 'vendeur', kw: ['produit', 'dupliquer', 'copier'], q: 'Puis-je dupliquer une fiche produit existante ?', a: 'Utilisez "Prévisualiser" puis republiez avec des modifications pour gagner du temps sur des produits similaires.' },
  { id: 'kb260', cat: 'vendeur_ventes', kw: ['export', 'données', 'ventes', 'télécharger'], q: 'Puis-je exporter mes données de ventes ?', a: 'Vos factures sont téléchargeables individuellement — un export global pourra être proposé prochainement.' },
  { id: 'kb261', cat: 'vendeur_conseil', kw: ['livraison', 'rapide', 'préparation'], q: 'Comment réduire mon temps de préparation ?', a: 'Organisez votre stock à l\'avance, préparez les commandes dès confirmation du paiement, et communiquez un statut clair au client pour rassurer sur les délais.' },
  { id: 'kb262', cat: 'livreur', kw: ['itinéraire', 'optimiser', 'plusieurs', 'livraisons'], q: 'Comment optimiser mon itinéraire pour plusieurs livraisons ?', a: 'Groupez les livraisons proches géographiquement quand c\'est possible et consultez la carte de suivi pour visualiser tous vos points de passage.' },
  { id: 'kb263', cat: 'affiliation', kw: ['statistiques', 'affiliation', 'suivre'], q: 'Comment suivre mes performances d\'affiliation ?', a: 'Votre tableau de bord affilié affiche le nombre de filleuls, les commissions générées et l\'évolution dans le temps.' },
  { id: 'kb264', cat: 'securite', kw: ['email', 'phishing', 'suspect', 'faux'], q: 'J\'ai reçu un email suspect prétendant venir de SINE.SHOP', a: 'Ne cliquez sur aucun lien et ne communiquez aucune information. Nos emails officiels proviennent toujours de @sineshophome.com — signalez tout doute au support.' },
  { id: 'kb265', cat: 'general', kw: ['nouveautés', 'mises à jour', 'récentes'], q: 'Où voir les nouveautés de la plateforme ?', a: 'Consultez régulièrement la page d\'accueil et vos notifications — les nouvelles fonctionnalités y sont annoncées.' },
  { id: 'kb266', cat: 'compte', kw: ['profil', 'photo', 'changer', 'avatar'], q: 'Comment changer ma photo de profil ?', a: 'Depuis Section Profil, cliquez sur votre photo puis "Modifier" pour en téléverser une nouvelle.' },
  { id: 'kb267', cat: 'commande', kw: ['commande', 'partager', 'proche'], q: 'Puis-je commander pour quelqu\'un d\'autre ?', a: 'Oui, indiquez simplement l\'adresse de livraison de la personne concernée au moment de la commande.' },
  { id: 'kb268', cat: 'produit', kw: ['produit', 'international', 'importé'], q: 'Les produits sont-ils tous locaux ?', a: 'La majorité des produits proviennent de vendeurs locaux, mais certains articles importés peuvent être proposés selon les vendeurs.' },
  { id: 'kb269', cat: 'vendeur', kw: ['abonnement', 'frais', 'inscription', 'vendeur'], q: 'Y a-t-il des frais d\'inscription pour devenir vendeur ?', a: 'Non, l\'inscription vendeur est gratuite — seule une commission de 5% est prélevée sur les ventes effectivement réalisées.' },
  { id: 'kb270', cat: 'livreur', kw: ['frais', 'inscription', 'devenir', 'livreur'], q: 'Y a-t-il des frais pour devenir livreur ?', a: 'Non, l\'inscription livreur est entièrement gratuite.' },
  { id: 'kb271', cat: 'compte', kw: ['âge', 'minimum', 'mineur'], q: 'Y a-t-il un âge minimum pour s\'inscrire ?', a: 'SINE.SHOP est réservé aux personnes majeures conformément à nos conditions générales d\'utilisation.' },
  { id: 'kb272', cat: 'paiement', kw: ['frais', 'transaction', 'caché'], q: 'Y a-t-il des frais cachés lors du paiement ?', a: 'Non, le montant affiché avant validation (articles + livraison + taxes) est exactement ce que vous payez, sans surprise.' },
  { id: 'kb273', cat: 'vendeur_ventes', kw: ['taxes', 'impôts', 'déclaration', 'revenus'], q: 'Dois-je déclarer mes revenus de vente ?', a: 'Les obligations fiscales relèvent de votre responsabilité personnelle selon la législation de votre pays — SINE.SHOP fournit vos factures comme justificatifs.' },
  { id: 'kb274', cat: 'general', kw: ['siège', 'bureaux', 'localisation', 'entreprise'], q: 'Où est basé SINE.SHOP ?', a: 'SINE.SHOP est basé à Abidjan, Côte d\'Ivoire.' },


];

module.exports = { KNOWLEDGE_BASE };
