// =========================================================
// SINE.SHOP — PEUPLEMENT DE LA BASE DE CONNAISSANCES ASSISTANT
// À exécuter UNE FOIS après déploiement : node scripts/seedFaq.js
// Peut être ré-exécuté sans risque (upsert par question — ne duplique
// jamais une entrée déjà présente).
//
// Ce premier lot couvre en profondeur les 10 catégories (achat, vente,
// livraison, paiement, compte, kyc, affiliation, messagerie, litiges,
// legal, general) — une base solide et immédiatement exploitable.
// Pour continuer à l'enrichir vers une couverture encore plus large,
// deux options : relancer ce script après avoir ajouté des entrées dans
// le tableau EOF ci-dessous, ou utiliser l'interface admin déjà
// construite (POST/PUT/DELETE /api/faq, réservée aux rôles admin).
// =========================================================

require('dotenv').config();
const mongoose = require('mongoose');
const FaqEntry = require('../models/FaqEntry');

const entries = [
  // ===================== ACHAT =====================
  { category: 'achat', question: "Comment passer une commande sur SINE.SHOP ?", answer: "Ajoutez les articles souhaités à votre panier depuis leur fiche produit, puis rendez-vous dans votre panier pour vérifier les quantités et options choisies (taille, couleur...). Cliquez ensuite sur \"Commander\", renseignez votre adresse de livraison, choisissez votre mode de paiement, et validez. Vous recevrez une confirmation immédiate et pourrez suivre votre commande en temps réel.", keywords: ['acheter', 'commander', 'achat'] },
  { category: 'achat', question: "Comment suivre ma commande ?", answer: "Depuis votre espace client, section \"Commandes\", cliquez sur la commande concernée puis sur \"Suivre ma commande\". Vous verrez son statut en temps réel (en préparation, expédiée, en livraison, livrée), avec la position en direct du livreur une fois la commande prise en charge.", keywords: ['suivi', 'tracking', 'où est ma commande'] },
  { category: 'achat', question: "Puis-je modifier ma commande après l'avoir passée ?", answer: "Une commande ne peut plus être modifiée une fois validée (articles, quantités, adresse). Si elle n'a pas encore été préparée par le vendeur, vous pouvez l'annuler depuis votre espace client et en passer une nouvelle avec les bonnes informations.", keywords: ['modifier commande', 'changer commande'] },
  { category: 'achat', question: "Comment annuler une commande ?", answer: "Depuis votre espace client, section \"Commandes\", ouvrez la commande concernée et cliquez sur \"Annuler\". L'annulation n'est possible que tant que la commande n'a pas été expédiée. Si vous avez payé en ligne, le remboursement suit la procédure habituelle de votre moyen de paiement.", keywords: ['annuler', 'annulation'] },
  { category: 'achat', question: "Ma commande contient des articles de plusieurs vendeurs, comment ça se passe ?", answer: "Si votre panier contient des articles de plusieurs boutiques différentes, SINE.SHOP crée automatiquement une commande distincte par vendeur (chacune avec son propre suivi et sa propre livraison), mais vous ne payez qu'une seule fois pour l'ensemble.", keywords: ['plusieurs vendeurs', 'multi vendeur'] },
  { category: 'achat', question: "Comment retourner un article ou demander un remboursement ?", answer: "Contactez directement le vendeur via la messagerie intégrée depuis la fiche de votre commande, en expliquant le motif du retour. S'il n'y a pas d'accord, vous pouvez ouvrir un litige depuis votre espace client pour qu'un membre de notre équipe intervienne.", keywords: ['retour', 'remboursement', 'rembourser'] },
  { category: 'achat', question: "Comment ajouter un produit à mes favoris ?", answer: "Sur la fiche d'un produit ou depuis les listes de produits, cliquez sur l'icône en forme de cœur. Vous retrouverez tous vos favoris dans la section \"Favoris\" de votre espace client.", keywords: ['favoris', 'wishlist'] },
  { category: 'achat', question: "Comment comparer plusieurs produits entre eux ?", answer: "Cliquez sur l'icône de comparaison présente sur chaque carte produit (jusqu'à 4 produits en même temps). Une bannière apparaît en bas de l'écran vous permettant d'ouvrir la comparaison côte à côte, avec une recommandation automatique basée sur les avis, les vues et le prix.", keywords: ['comparer', 'comparaison'] },
  { category: 'achat', question: "Comment réserver un produit au lieu de l'acheter directement ?", answer: "Certains produits proposent une option \"Réserver\" en plus de \"Ajouter au panier\". La réservation vous permet de mettre l'article de côté chez le vendeur ; vous recevez une confirmation dès sa création, consultable dans la section \"Réservations\" de votre espace.", keywords: ['réservation', 'réserver'] },
  { category: 'achat', question: "Comment partager une fiche produit à quelqu'un ?", answer: "Cliquez sur l'icône de partage présente sur chaque carte produit. Sur mobile, cela ouvre le sélecteur de partage natif de votre téléphone (WhatsApp, SMS...) ; sur ordinateur, le lien est copié dans votre presse-papiers.", keywords: ['partager produit', 'envoyer lien'] },
  { category: 'achat', question: "Comment consulter le profil public d'un vendeur ?", answer: "Cliquez sur le nom ou la photo du vendeur depuis n'importe quelle fiche produit. Vous verrez sa note, le nombre de ses produits en ligne, et pourrez le contacter directement.", keywords: ['profil vendeur', 'voir vendeur'] },
  { category: 'achat', question: "Que faire si un produit est en rupture de stock ?", answer: "Un badge \"Rupture\" s'affiche sur les produits indisponibles. Vous pouvez tout de même l'ajouter à vos favoris pour suivre sa disponibilité, ou contacter le vendeur directement pour savoir quand il sera réapprovisionné.", keywords: ['rupture de stock', 'indisponible'] },
  { category: 'achat', question: "Puis-je acheter en tant qu'invité, sans créer de compte ?", answer: "Non, un compte client est nécessaire pour passer commande sur SINE.SHOP — cela nous permet de vous garantir un vrai suivi de commande, un historique, et un accès à la messagerie avec le vendeur en cas de besoin. La création de compte est gratuite et rapide.", keywords: ['sans compte', 'invité', 'guest'] },

  // ===================== VENTE =====================
  { category: 'vente', question: "Comment devenir vendeur sur SINE.SHOP ?", answer: "Inscrivez-vous via le formulaire dédié aux vendeurs, renseignez les informations de votre boutique, puis complétez la vérification d'identité (KYC) demandée pour activer les paiements. Une fois votre compte vérifié, vous pouvez publier vos premiers produits.", keywords: ['devenir vendeur', 'inscription vendeur', 'ouvrir boutique'] },
  { category: 'vente', question: "Comment publier un nouveau produit ?", answer: "Depuis votre espace vendeur, section \"Produits\", cliquez sur \"Ajouter un produit\". Renseignez le nom, la catégorie, le prix, les photos/vidéos, et les caractéristiques spécifiques à votre type de produit (taille et couleur pour un vêtement, stockage pour un smartphone, etc. — les champs s'adaptent automatiquement à la catégorie choisie).", keywords: ['publier produit', 'ajouter produit', 'créer une annonce'] },
  { category: 'vente', question: "Quelle commission SINE.SHOP prend-elle sur mes ventes ?", answer: "Une commission est prélevée sur chaque vente réalisée, calculée sur le sous-total de la commande (hors frais de livraison). Le détail exact du taux appliqué est visible dans votre tableau de bord vendeur, section revenus.", keywords: ['commission', 'frais', 'pourcentage vente'] },
  { category: 'vente', question: "Comment gérer mes commandes en tant que vendeur ?", answer: "Depuis votre espace vendeur, section \"Commandes\", vous voyez toutes les commandes reçues. Vous pouvez y assigner un livreur, marquer la commande comme expédiée, et suivre son statut jusqu'à la livraison.", keywords: ['gérer commandes vendeur', 'commandes reçues'] },
  { category: 'vente', question: "Comment modifier ou supprimer un produit déjà publié ?", answer: "Depuis votre espace vendeur, section \"Produits\", ouvrez le produit concerné pour modifier son prix, ses photos, son stock ou ses informations. Un bouton \"Supprimer\" permet de le retirer définitivement de la vente.", keywords: ['modifier produit', 'supprimer produit', 'retirer produit'] },
  { category: 'vente', question: "Comment sont calculées mes statistiques de vente ?", answer: "Votre tableau de bord vendeur affiche vos ventes totales, votre chiffre d'affaires, vos produits les plus consultés et les plus vendus, actualisés en temps réel à chaque nouvelle commande confirmée.", keywords: ['statistiques', 'chiffre d\'affaires', 'ventes'] },
  { category: 'vente', question: "Comment recevoir le paiement de mes ventes ?", answer: "Les paiements de vos ventes sont crédités sur votre solde vendeur après confirmation de la commande. Vous pouvez ensuite demander un retrait vers votre moyen de paiement enregistré depuis votre espace vendeur.", keywords: ['recevoir paiement', 'retrait vendeur', 'être payé'] },
  { category: 'vente', question: "Pourquoi dois-je vérifier mon identité (KYC) pour vendre ?", answer: "La vérification d'identité protège l'ensemble de la communauté SINE.SHOP contre la fraude et garantit que chaque boutique est tenue par une personne réelle et identifiable. Elle est obligatoire avant de pouvoir recevoir des paiements.", keywords: ['kyc vendeur', 'vérification identité vendeur'] },
  { category: 'vente', question: "Comment créer une nouvelle catégorie de produit ?", answer: "Si aucune catégorie existante ne correspond à votre produit, vous pouvez en créer une nouvelle directement depuis le formulaire de publication, en choisissant \"Autre / nouvelle catégorie\" et en la nommant vous-même.", keywords: ['créer catégorie', 'nouvelle catégorie'] },
  { category: 'vente', question: "Comment répondre aux avis laissés sur mes produits ?", answer: "Les avis clients sont visibles depuis votre espace vendeur, section \"Avis\". Vous pouvez y répondre publiquement pour remercier, clarifier un point, ou proposer une solution en cas d'avis négatif.", keywords: ['avis', 'répondre avis', 'notes clients'] },
  { category: 'vente', question: "Puis-je gérer plusieurs rôles (vendeur ET client par exemple) avec un seul compte ?", answer: "Oui, SINE.SHOP prend en charge les comptes multi-rôles. Depuis les paramètres de votre espace, vous pouvez activer un rôle supplémentaire (client, vendeur, livreur ou affilié) sans avoir à créer un second compte.", keywords: ['multi-rôle', 'plusieurs rôles', 'cumuler rôles'] },
  { category: 'vente', question: "Que se passe-t-il si je ne livre pas une commande à temps ?", answer: "Des délais de livraison excessifs ou récurrents peuvent affecter votre note vendeur et déclencher un signalement du client. Nous recommandons de toujours tenir votre stock à jour et de communiquer avec le client via la messagerie en cas de retard imprévu.", keywords: ['retard livraison vendeur', 'délai non respecté'] },

  // ===================== LIVRAISON =====================
  { category: 'livraison', question: "Comment devenir livreur sur SINE.SHOP ?", answer: "Inscrivez-vous via le formulaire dédié aux livreurs, renseignez votre véhicule et votre zone de couverture, puis complétez la vérification d'identité (KYC). Une fois votre compte vérifié, vous pouvez être assigné à des livraisons.", keywords: ['devenir livreur', 'inscription livreur'] },
  { category: 'livraison', question: "Comment fonctionne le suivi en temps réel de ma livraison ?", answer: "Une fois votre commande prise en charge par un livreur, sa position est partagée en direct sur la page de suivi (carte en temps réel), avec une mise à jour automatique dès que son statut change (récupérée, en route, livrée).", keywords: ['suivi temps réel', 'position livreur'] },
  { category: 'livraison', question: "Quels sont les délais de livraison habituels ?", answer: "Les délais varient selon la zone de livraison et le vendeur. Une estimation est affichée sur la page de suivi de votre commande dès sa prise en charge.", keywords: ['délai livraison', 'combien de temps'] },
  { category: 'livraison', question: "Comment un livreur récupère-t-il une commande chez le vendeur ?", answer: "Une fois assigné à une commande par le vendeur ou un administrateur, le livreur voit apparaître la livraison dans son espace, avec l'adresse de récupération. Il met à jour le statut à \"récupérée\" une fois l'article en main, puis \"livrée\" une fois remise au client.", keywords: ['récupérer commande', 'prise en charge livreur'] },
  { category: 'livraison', question: "Que faire si le client est absent lors de la livraison ?", answer: "Contactez le client via la messagerie intégrée ou l'appel depuis l'application pour convenir d'un nouveau créneau. Ne laissez jamais un colis sans confirmation du client.", keywords: ['client absent', 'personne à la livraison'] },
  { category: 'livraison', question: "Comment activer le partage de ma position en tant que livreur ?", answer: "Depuis votre espace livreur, autorisez l'accès à votre position lorsque votre navigateur ou application vous le demande. Votre position est alors partagée automatiquement avec les clients dont vous livrez la commande, et jamais en dehors de ces livraisons actives.", keywords: ['partage position', 'géolocalisation livreur'] },
  { category: 'livraison', question: "Le paiement à la livraison (cash) est-il possible ?", answer: "Oui, si le vendeur propose cette option, vous pouvez choisir \"Paiement à la livraison\" lors de la validation de votre commande. Le montant est alors réglé directement au livreur au moment de la remise du colis.", keywords: ['paiement à la livraison', 'cash', 'espèces'] },

  // ===================== PAIEMENT =====================
  { category: 'paiement', question: "Quels moyens de paiement sont acceptés sur SINE.SHOP ?", answer: "SINE.SHOP accepte le paiement mobile (Orange Money, Wave, MTN Money...), la carte bancaire (Visa/Mastercard), SINE.PAY (notre solution intégrée), et le paiement à la livraison lorsque le vendeur le propose.", keywords: ['moyens de paiement', 'comment payer'] },
  { category: 'paiement', question: "Le paiement en ligne est-il sécurisé ?", answer: "Oui. Tous les paiements en ligne passent par des passerelles sécurisées (CinetPay) qui chiffrent vos informations bancaires — SINE.SHOP ne stocke jamais vos données de carte bancaire directement.", keywords: ['sécurité paiement', 'paiement sécurisé'] },
  { category: 'paiement', question: "Comment obtenir la facture d'une commande ?", answer: "Depuis votre espace client, section \"Commandes\", cliquez sur \"Facture\" à côté de la commande concernée. Un document PDF/imprimable s'ouvre avec le détail complet de votre achat, prêt à être téléchargé ou imprimé.", keywords: ['facture', 'reçu', 'justificatif'] },
  { category: 'paiement', question: "Que faire si mon paiement échoue ?", answer: "Vérifiez d'abord le solde et la validité de votre moyen de paiement. Si le problème persiste, réessayez avec un autre mode de paiement, ou contactez notre support si le montant a été débité sans confirmation de commande.", keywords: ['paiement échoué', 'paiement refusé'] },
  { category: 'paiement', question: "Qu'est-ce que SINE.PAY ?", answer: "SINE.PAY est la solution de paiement propre à SINE.SHOP, qui vous permet de régler vos achats directement depuis la plateforme, avec un récapitulatif détaillé (sous-total, frais de livraison, commission) avant validation finale.", keywords: ['sinepay', 'sine.pay'] },
  { category: 'paiement', question: "Comment fonctionne le remboursement en cas d'annulation ?", answer: "Si vous avez payé en ligne et que la commande est annulée avant expédition, le remboursement est traité vers votre moyen de paiement d'origine. Le délai dépend de votre banque ou opérateur mobile.", keywords: ['remboursement', 'être remboursé'] },
  { category: 'paiement', question: "Pourquoi vois-je des frais de livraison et une commission dans le récapitulatif ?", answer: "Le sous-total correspond au prix des articles, les frais de livraison rémunèrent le transport, et la commission est celle prélevée par la plateforme sur la vente. Ces trois montants s'additionnent pour former le total à payer, toujours détaillé avant validation.", keywords: ['frais de livraison', 'détail du prix'] },

  // ===================== COMPTE =====================
  { category: 'compte', question: "Comment créer un compte sur SINE.SHOP ?", answer: "Cliquez sur \"Créer un compte\" depuis la page de connexion, choisissez votre profil (client, vendeur, livreur ou affilié), renseignez vos informations, puis vérifiez votre adresse email via le lien reçu.", keywords: ['créer un compte', 'inscription', 's\'inscrire'] },
  { category: 'compte', question: "J'ai oublié mon mot de passe, comment le réinitialiser ?", answer: "Depuis la page de connexion, cliquez sur \"Mot de passe oublié\", renseignez votre email ou numéro de téléphone, puis suivez les instructions envoyées pour créer un nouveau mot de passe.", keywords: ['mot de passe oublié', 'réinitialiser mot de passe'] },
  { category: 'compte', question: "Comment vérifier mon adresse email ?", answer: "Un email contenant un lien de vérification vous est envoyé automatiquement à l'inscription. Cliquez sur ce lien pour activer pleinement votre compte. Si vous ne l'avez pas reçu, vous pouvez en redemander un depuis votre espace.", keywords: ['vérifier email', 'confirmer email'] },
  { category: 'compte', question: "Comment changer la langue de l'application ?", answer: "Depuis les paramètres de votre espace, choisissez votre langue préférée (français, anglais, espagnol ou arabe). L'application peut aussi détecter automatiquement la langue de votre système si vous activez cette option.", keywords: ['changer langue', 'langue application'] },
  { category: 'compte', question: "Comment changer le thème (clair/sombre) de l'application ?", answer: "Depuis les paramètres, choisissez entre le thème clair, le thème sombre, ou \"système\" pour que l'application suive automatiquement le réglage de votre téléphone ou ordinateur.", keywords: ['thème sombre', 'mode sombre', 'dark mode'] },
  { category: 'compte', question: "Comment masquer temporairement mon compte ?", answer: "Depuis les paramètres de votre espace, section \"Gestion du compte\", cliquez sur \"Masquer temporairement\". Une demande est envoyée à notre équipe pour traitement — votre compte reste actif tant qu'elle n'a pas été validée.", keywords: ['masquer compte', 'suspendre compte'] },
  { category: 'compte', question: "Comment fermer mon compte ?", answer: "Depuis les paramètres de votre espace, section \"Gestion du compte\", cliquez sur \"Fermer le compte\". Une demande est envoyée à notre équipe pour traitement — votre compte reste actif tant qu'elle n'a pas été validée.", keywords: ['fermer compte', 'désactiver compte'] },
  { category: 'compte', question: "Comment supprimer définitivement mon compte ?", answer: "Depuis les paramètres de votre espace, section \"Gestion du compte\", cliquez sur \"Supprimer définitivement\". Une demande est envoyée à notre équipe, et vous êtes immédiatement déconnecté(e) — votre compte est ensuite supprimé après validation par un administrateur.", keywords: ['supprimer compte', 'suppression définitive'] },
  { category: 'compte', question: "Comment modifier mes informations personnelles ?", answer: "Depuis votre espace, section \"Profil\", vous pouvez modifier votre nom, votre photo, votre numéro de téléphone et votre adresse à tout moment.", keywords: ['modifier profil', 'changer informations'] },
  { category: 'compte', question: "Puis-je me connecter avec Google ou Facebook ?", answer: "Oui, la connexion via Google ou Facebook est proposée sur la page de connexion en plus de l'email et du mot de passe classiques.", keywords: ['connexion google', 'connexion facebook'] },
  { category: 'compte', question: "Ma session se déconnecte-t-elle automatiquement ?", answer: "Non, une fois connecté, votre session reste active aussi longtemps que vous utilisez l'application normalement — elle se renouvelle automatiquement en arrière-plan, sans jamais vous déconnecter de force.", keywords: ['session expire', 'déconnexion automatique'] },

  // ===================== KYC =====================
  { category: 'kyc', question: "Qu'est-ce que la vérification d'identité (KYC) ?", answer: "Le KYC (\"Know Your Customer\") est une vérification d'identité obligatoire pour les vendeurs, livreurs et affiliés avant de pouvoir recevoir des paiements sur la plateforme. Elle consiste à soumettre une pièce d'identité officielle (carte nationale, passeport ou permis de conduire).", keywords: ['kyc', 'vérification identité', 'pièce d\'identité'] },
  { category: 'kyc', question: "Quels documents sont acceptés pour le KYC ?", answer: "Carte nationale d'identité, passeport, ou permis de conduire. Pour la carte d'identité et le permis, le recto ET le verso sont demandés ; pour le passeport, seule la page d'identité est nécessaire.", keywords: ['documents kyc', 'pièces acceptées'] },
  { category: 'kyc', question: "Combien de temps prend la vérification KYC ?", answer: "Votre dossier est examiné par notre équipe dans les meilleurs délais après soumission. Vous recevez un email dès qu'une décision est prise (approuvé ou rejeté, avec le motif dans ce dernier cas).", keywords: ['délai kyc', 'temps de vérification'] },
  { category: 'kyc', question: "Mon KYC a été rejeté, que faire ?", answer: "L'email de rejet précise le motif. Vous pouvez soumettre de nouveaux documents depuis votre espace en tenant compte de la raison indiquée (photo illisible, document expiré, informations non correspondantes...).", keywords: ['kyc rejeté', 'kyc refusé'] },

  // ===================== AFFILIATION =====================
  { category: 'affiliation', question: "Comment fonctionne le programme d'affiliation SINE.SHOP ?", answer: "En tant qu'affilié, vous recevez un code de parrainage unique à partager. Chaque nouvelle inscription via votre code vous rapporte un bonus fixe, et vous touchez ensuite une commission sur les achats réalisés par les personnes que vous avez parrainées.", keywords: ['programme affiliation', 'parrainage', 'affilié'] },
  { category: 'affiliation', question: "Comment devenir affilié ?", answer: "Inscrivez-vous via le formulaire dédié à l'affiliation depuis la page de connexion. Une fois votre compte créé, votre code de parrainage personnel est généré automatiquement.", keywords: ['devenir affilié', 'inscription affiliation'] },
  { category: 'affiliation', question: "Comment suivre mes gains d'affiliation ?", answer: "Votre espace affilié affiche en temps réel le nombre de vos filleuls, le total de vos commissions, et l'historique détaillé de chaque gain.", keywords: ['gains affiliation', 'suivi commissions'] },
  { category: 'affiliation', question: "Comment retirer mes gains d'affiliation ?", answer: "Depuis votre espace affilié, section \"Retraits\", demandez un retrait vers votre moyen de paiement enregistré. Des règles minimales (montant minimum, ancienneté du compte) peuvent s'appliquer, précisées directement dans cette section.", keywords: ['retirer gains', 'retrait affiliation'] },

  // ===================== MESSAGERIE =====================
  { category: 'messagerie', question: "Comment contacter un vendeur ?", answer: "Depuis le profil du vendeur ou une fiche produit, cliquez sur \"Contacter\". Une conversation s'ouvre dans votre messagerie, où vous pouvez échanger du texte, des photos, votre position, ou même passer un appel vocal ou vidéo.", keywords: ['contacter vendeur', 'écrire au vendeur'] },
  { category: 'messagerie', question: "Comment passer un appel vocal ou vidéo depuis la messagerie ?", answer: "Ouvrez une conversation, puis cliquez sur l'icône téléphone (appel vocal) ou caméra (appel vidéo) en haut de l'écran de discussion.", keywords: ['appel vocal', 'appel vidéo', 'appeler'] },
  { category: 'messagerie', question: "Comment envoyer un message vocal ?", answer: "Dans une conversation, appuyez sur l'icône micro à côté de la zone de texte pour démarrer l'enregistrement, puis validez pour l'envoyer ou annulez si besoin.", keywords: ['message vocal', 'note vocale'] },
  { category: 'messagerie', question: "Comment modifier ou supprimer un message envoyé ?", answer: "Un message peut être modifié dans les 10 minutes suivant son envoi (votre interlocuteur voit alors la mention \"modifié\"). La suppression, elle, ne masque le message que de votre propre vue — il reste visible pour votre interlocuteur, pour des raisons de sécurité.", keywords: ['modifier message', 'supprimer message'] },
  { category: 'messagerie', question: "Comment bloquer quelqu'un dans la messagerie ?", answer: "Ouvrez la conversation concernée, cliquez sur le menu à trois points en haut à droite, puis \"Bloquer\". Vous ne pourrez alors plus échanger de messages tant que vous ne le débloquez pas.", keywords: ['bloquer utilisateur', 'bloquer contact'] },
  { category: 'messagerie', question: "Comment changer le fond d'une conversation ?", answer: "Ouvrez la conversation, cliquez sur le menu à trois points puis \"Changer le fond\". Vous pouvez choisir parmi plusieurs fonds prédéfinis, ou importer une photo depuis votre téléphone.", keywords: ['fond conversation', 'wallpaper', 'arrière-plan discussion'] },
  { category: 'messagerie', question: "Comment traduire automatiquement un message ?", answer: "Survolez (ou restez appuyé sur mobile) le message à traduire, puis cliquez sur l'icône de traduction. La traduction s'affiche directement sous le message original, dans votre langue préférée.", keywords: ['traduire message', 'traduction automatique'] },
  { category: 'messagerie', question: "Comment partager le lien d'une commande ou d'une facture dans un message ?", answer: "Depuis votre espace, ouvrez la commande ou la facture concernée puis utilisez le bouton \"Partager\" — vous pouvez alors l'envoyer directement dans une conversation existante.", keywords: ['partager commande', 'partager facture'] },

  // ===================== LITIGES =====================
  { category: 'litiges', question: "Comment signaler un problème avec une commande ?", answer: "Essayez d'abord de contacter le vendeur via la messagerie pour trouver une solution à l'amiable. Si aucun accord n'est trouvé, ouvrez un litige depuis la fiche de votre commande pour qu'un membre de notre équipe examine la situation.", keywords: ['signaler problème', 'ouvrir litige'] },
  { category: 'litiges', question: "Que faire si je reçois un article différent de ce que j'ai commandé ?", answer: "Contactez immédiatement le vendeur via la messagerie avec des photos de l'article reçu. Si le désaccord persiste, ouvrez un litige pour qu'une solution (remboursement, échange) soit trouvée avec l'aide de notre équipe.", keywords: ['article différent', 'mauvais article'] },
  { category: 'litiges', question: "Comment signaler un utilisateur qui a un comportement abusif ?", answer: "Depuis la conversation concernée, utilisez le menu à trois points pour bloquer l'utilisateur, puis contactez notre support pour signaler la situation avec le maximum de détails possible.", keywords: ['signaler utilisateur', 'comportement abusif'] },

  // ===================== LEGAL =====================
  { category: 'legal', question: "Où puis-je consulter les conditions générales d'utilisation (CGU) ?", answer: "Les conditions générales d'utilisation sont accessibles depuis le pied de page de n'importe quelle page de SINE.SHOP, ou directement via la page dédiée \"CGU\".", keywords: ['cgu', 'conditions utilisation'] },
  { category: 'legal', question: "Où puis-je consulter les conditions générales de vente (CGV) ?", answer: "Les conditions générales de vente sont accessibles depuis le pied de page de n'importe quelle page de SINE.SHOP, ou directement via la page dédiée \"CGV\".", keywords: ['cgv', 'conditions vente'] },
  { category: 'legal', question: "Comment SINE.SHOP protège-t-il mes données personnelles ?", answer: "Notre politique de confidentialité détaille précisément quelles données sont collectées, pourquoi, et comment elles sont protégées. Elle est accessible depuis le pied de page de l'application.", keywords: ['confidentialité', 'données personnelles', 'vie privée'] },
  { category: 'legal', question: "SINE.SHOP utilise-t-il des cookies ?", answer: "Oui, uniquement des cookies nécessaires au bon fonctionnement du site (connexion, préférences). Le détail complet est disponible dans notre politique de cookies, accessible depuis le pied de page.", keywords: ['cookies', 'politique cookies'] },

  // ===================== GENERAL =====================
  { category: 'general', question: "Qu'est-ce que SINE.SHOP ?", answer: "SINE.SHOP est une marketplace qui met en relation clients, vendeurs, livreurs et affiliés autour de tout type de produit — vêtements, électronique, alimentation, services, et bien plus. Chacun peut y créer son espace selon son besoin : acheter, vendre, livrer, ou générer des revenus par le parrainage.", keywords: ['sineshop', 'c\'est quoi sineshop', 'à propos'] },
  { category: 'general', question: "Comment contacter le support SINE.SHOP ?", answer: "Depuis votre espace, section \"Aide\", vous pouvez écrire directement à notre équipe support par email ou WhatsApp. Nous répondons dans les meilleurs délais.", keywords: ['contacter support', 'aide', 'assistance'] },
  { category: 'general', question: "SINE.SHOP est-il disponible sur mobile ?", answer: "Oui, SINE.SHOP fonctionne sur tout type d'appareil (téléphone, tablette, ordinateur) directement depuis votre navigateur, avec une interface qui s'adapte automatiquement à la taille de votre écran.", keywords: ['application mobile', 'sur téléphone'] },
  { category: 'general', question: "Comment changer la devise affichée sur SINE.SHOP ?", answer: "Depuis les paramètres de votre espace, choisissez votre devise préférée. Tous les prix affichés sont alors automatiquement convertis.", keywords: ['changer devise', 'monnaie'] },
];

async function seed() {
  const mongoUri = process.env.MONGODB_URI || process.env.MONGO_URI;
  if (!mongoUri) {
    console.error('MONGODB_URI manquant dans .env — impossible de peupler la base.');
    process.exit(1);
  }

  await mongoose.connect(mongoUri);
  console.log('Connecté à MongoDB.');

  let created = 0, skipped = 0;
  for (const entry of entries) {
    const exists = await FaqEntry.findOne({ question: entry.question });
    if (exists) { skipped++; continue; }
    await FaqEntry.create(entry);
    created++;
  }

  console.log(`Terminé : ${created} entrée(s) créée(s), ${skipped} déjà existante(s) (ignorée(s)).`);
  await mongoose.disconnect();
}

seed().catch(err => {
  console.error('Erreur lors du peuplement :', err);
  process.exit(1);
});
